services:
  app:
    build: .
    container_name: cache-lab
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7.4.1
    container_name: redis-cache
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:2.70
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight:/data

volumes:
  redis_data:
  redis_insight: